name: push

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test
    - name: Publish Nuget Panosen.CodeDom.Sqlite
      run: dotnet nuget push Panosen.CodeDom.Sqlite/bin/Release/Panosen.CodeDom.Sqlite.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
    - name: Publish Nuget Panosen.CodeDom.Sqlite.Engine
      run: dotnet nuget push Panosen.CodeDom.Sqlite.Engine/bin/Release/Panosen.CodeDom.Sqlite.Engine.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
